version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: find-a-friend
    command: --default-authentication-plugin=caching_sha2_password
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: find-a-friend
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - '3306:3306'
volumes: # add persistent data even if container is removed.
  mysqldb: