name: Run E2E Tests

on: [push]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      find-a-friend-pg:                           #nome do serviço
        image: bitnami/postgresql:latest    #imagem que vamos usar
        ports:                              #portas que vamos usar
            - 5432:5432
        env:                        #variáveis de ambiente
          POSTGRES_USERNAME: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DATABASE: find-a-friend

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - run: npm ci
    - run: npm run pretest:e2e
    - run: npm run test:e2e
      env:
        JWT_TOKEN: test
        DATABASE_URL: "postgresql://docker:docker@localhost:5432/find-a-friend?schema=public"
        CPF_TEST: "56845241186"